### PR TITLE
Add Selection/Displaying method

### PR DESCRIPTION
**Pull request by ikeisuke**
I've added selection events/methods and dislaying event, as I needed for my apps.
I thought I'd send over the changes in case you want to include it in the master.

Thanks for your great work on the library, it's making "customized view" much easier for me!

### CODE REVIEW

**Comment by Xenofex** [comment]
Hi, @ikeisuke 

Thanks a lot for contributing!

I'm just back from my holidays and has reviewed your commits. The scrolling and events work great and integrate well with the existing code. However the selection part, I feel like it not a perfect solution.

Unlike the UITableViewCell, my stream view cell is an arbitrary UIView instead of that you have to inherit some class. The UITableViewCell provides you some basic features like the title/subtitle label, the image view, the accessory view, as well as the selection. But most of the time I have to add my own views to the UITableViewCell because the default view cannot satisfy my use case 100%. As a result the I choose the custom UIView as the stream view's cell, leaving the application to implement the logic inside.

Given a UIView, it's not hard to implement the selection behavior. You can make it a UIButton or any means you like. Forcing the application programmer to implement `setSelected:animated:` even with an default empty implementation feels too intrusive for me.

Could you please remove the selection part, leaving only the scrolling and events? Thanks again for the commits!

**Comment by ikeisuke** [comment]
Thanks for your reviewing.

I think so too. you said 

<blockquote>Forcing the application programmer to implement setSelected:animated: even with an default empty implementation feels too intrusive for me.</blockquote>

It is an expedient adopted only in desperation.

Let me see if I've got this straight.
What you're saying is to remove selected property and <code>setSelected:animated:</code> on EKResusableCell,or to leave only <code>scrollToCellAtIndex:atScrollPosition:animated:</code> on EKStreamView.

Would you let me know?

**Comment by Xenofex** [comment]
Yes, do both of them, I suggest. Scrolling and will/did display events are great.

**Comment by ikeisuke** [comment]
I'm not sure I understand what you mean, yet I make new commit scroll, displaying and selection.
If you want no selection methods. Could you cherry-pick scroll and displaying?

**Comment by Xenofex** [comment]
The first 2 are what I want, aka 4abfeb4 and b6709e0. The last one, 0f4396b should be discarded.

**Comment by ikeisuke** [comment]
I got it.
I discarded the last one.

**Comment by Xenofex** [comment]
Great!

**Pull request merged**
